version: '3.7'
services:
  database:
    image: postgres:12-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
  
  api:
    image: ajialy-api
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: sh -c 'yarn database:setup && yarn prisma generate && yarn start'
    environment:
      DATABASE_URL: postgresql://postgres@database:5432/mydb?schema=public
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '3000:3000'