name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Setup database and client
        run: yarn setup
        env:
          DATABASE_URL: 'postgresql://postgres@localhost:5432/mydb?schema=public'

      - name: Run lint
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Run E2E tests
        run: yarn jest --config ./test/jest-e2e.json
        env:
          DATABASE_URL: 'postgresql://postgres@localhost:5432/mydb?schema=public'
